name: Notebook Execution and Validation

on: 
  pull_request:
    branches:
      - main
    paths:
      - 'notebooks/**.ipynb'
      - '*.yml'
      
env:
  CASJOBS_PW: ${{ secrets.CASJOBS_PW }}
  CASJOBS_USERID: ${{ secrets.CASJOBS_USERID }}

jobs:
  NotebookExecutionValidation:
   uses: TheRealZoidberg/reusableTest/.github/workflows/ci_runner.yml@testing2
   
  ExecuteNotebooks:
   uses: TheRealZoidberg/reusableTest/.github/workflows/genHtml.yml@testing2
